### ISSUE TITLE
Implement badges 

### ISSUE THREAD

**Issue by ChrisspyB** [iccaving/website#10]
Implement easy to use system of assigning badges to people. 

NB: I have some version of this working already, just making an issue to post updates on.

**Comment by ChrisspyB** [comment]
Due to popular demand, caver pages now have badges based on their number of trips, number of reports, number of caves and number of cavers.  The badges are svgs and are rendered as 32 * 32 px images. The images are stored on the server, so can be changed from the admin interface. I'll probably make this live in a few days.

Here's what it looks like with placeholder images, though unless someone has a particularly nice design the placeholders might be around for a while.

![Animated gif showing the badges in action.](https://user-images.githubusercontent.com/8879093/93000654-bfded880-f521-11ea-88e7-4f257ae60f7c.gif)


Still need to do badges which are awarded to individual members (e.g. Lightning, Evans' Sake). Plan is to make these awardable from the Edit Caver interface on icccadmin, so will require quite a different implementation.

**Comment by ChrisspyB** [comment]
Above is done. Like committee, there's a list of awardable badges in `contenttypes.yml` that will be updated if new badges are added.

**Comment by jarvist** [comment]
Does this mean we can now play Caver Top-Trumps until we're able to go caving again?

**Comment by ChrisspyB** [comment]
That was the first thing that came to my mind too!
I think at this rate, the whole website is going to turn into collection of 2000s-era flash games while I procrastinate my ESA.

**Comment by ChrisspyB** [comment]
Alrighty, should be live now.
