### ISSUE TITLE
Export data as csv 

### ISSUE THREAD

**Issue by jackHalliday** [iccaving/website#11]
Would be wonderful to export your cave data as something like a csv x

**Comment by jdhare** [comment]
Given the number of caving trips I've done, I would prefer a high compression format like HDF5 to keep the file size down.

**Comment by jackHalliday** [comment]
To clarify, ideal data format would look something like this:

`Trip date;   Name of cave; other person on trip 1, other person on trip2, ... ; url to report; `

The bit with other people on the trip is least important to me personally.

ty :)

**Comment by ChrisspyB** [comment]
Hiya,

Exporting to `.csv` should be easy to implement since most of the data is already collected in the caver page.  Should be in the tens of kB for even the most prolific caver.

The only new thing to collect is the other cavers on a specific trip. Displaying this might be a nice feature for the actual caver page too. Sketched out here:

![Screenshot 2020-01-25 at 16 46 22](https://user-images.githubusercontent.com/8879093/73124354-58741880-3f92-11ea-8ea4-5523161b7d85.png)

Slight risk that this will make the table a bit messy (e.g. all in Notts?), but there are various solutions to this.

**Comment by rhyst** [comment]
Implement carefully to avoid lots of db queries as they are slow af. I think there's similair examples of collecting all the IDs that need resolving into a single query.

**Comment by jackHalliday** [comment]
What kind of a name is Echo? :P

**Comment by ChrisspyB** [comment]
> Implement carefully to avoid lots of db queries as they are slow af. I think there's similair examples of collecting all the IDs that need resolving into a single query.

Fortunately no additional queries were required beyond what is already carried out by the caversearch function, just a few lines of php to combine it into a useful format. Here's a caver page now:

![Screenshot 2020-01-26 at 23 54 40](https://user-images.githubusercontent.com/8879093/73143994-6744f300-4098-11ea-99d0-a4a257dc17f5.png)

Thoughts on the aesthetics of this are appreciated, I can't decide whether it's too noisey or not.

Either way, the data is now all neatly collected so just needs to be made exportable.

**Comment by jdhare** [comment]
It's cool you can do this, very nice! However visually I think it's too
much stuff. That info is available via the trip report. If one is really
interested, one can export the list.

**Comment by jackHalliday** [comment]
Agree it looks a bit too busy.

If it was only given names that might make it work. Not sure how that would work with humans who's family name comes 1st (ie Ho Yan Jin) though.
J

Sent from my phone.

________________________________

**Comment by ChrisspyB** [comment]
Yeah I agree - I'll fiddle with making it toggleable and if nothing looks right I'll just remove it.

**Comment by ChrisspyB** [comment]
Changes are now live.
Trip data can be exported to csv via a link below the table of a user's trip reports.

The default presentation of the table has not been changed, but a button has been added to toggle between the default and a more detailed table, with is horizontally scrollable.
