### ISSUE TITLE
Site search

### ISSUE THREAD

**Issue by rhyst** [iccaving/website#12]
Bolt comes with search capabilities and I did make a template for the page so it looks alright:

https://union.ic.ac.uk/rcc/caving/search

But this is not linked anywhere at the moment. Worth checking if it actually searches in a useful fashion and if so linking it in sidebar?

**Comment by ChrisspyB** [comment]
I did a couple random of searches and was quite impressed with the results, not sure what to check beyond that.  I'll add it to the sidebar at some stage

**Comment by ChrisspyB** [comment]
Is is done.
