### ISSUE TITLE
Administration in menu is ugly

### ISSUE THREAD

**Issue by rhyst** [iccaving/website#13]
I don't know why I called it that. It should be "Log in" or something and then change to "Admin" or your username when you are logged in.

**Comment by ChrisspyB** [comment]
Sure

**Comment by ChrisspyB** [comment]
Now displays "Sign in" and "Admin". 
I moved it to the top of the sidebar partially because I think it's nicer, but mostly because sidebar caching made it awkward to put elsewhere.
