### ISSUE TITLE
Add committee positions field to cavers

### ISSUE THREAD

**Issue by rhyst** [iccaving/website#8]
Add a field for recording the committee positions a person held (with year of role). Must be able to hold multiple roles.

Automate generation of that list of past committee?

Badges for past and current committee.

**Comment by ChrisspyB** [comment]
As far as I can tell, there's no existing list of committee members beyond the [contacts page](https://union.ic.ac.uk/rcc/caving/page/contacts), so I've ripped its contents and made a .csv file.

I was considering reading directly from this .csv, but I reckon it'd be better to import this as a new table on the database e.g. ```bolt_committee```. Thoughts?

Either-way, I'm not how sure to associate a Caver's name in plain text to their actual profile in a systematic way, unless I create and populate a new column in the ```bolt_cavers``` table. But this sounds tedious, unless I scriptify it.

**Comment by rhyst** [comment]
Bolt has "repeater" fields which would work for this I think. See the cavepeeps field for how to set it up? Have you found the contenttypes.yml (I think)? That's where this sort of stuff is defined.

I think if you add the field like that then going through and manually adding the data is probably easier. I'm sure there are people with time on their hands and it's not so much data.

**Comment by ChrisspyB** [comment]
I believe this is all working now.

**Comment by rhyst** [comment]
Seems to work. One minor thing. In the committees tab on the admin screen, should 'summary' and 'body' be there?

**Comment by ChrisspyB** [comment]
Oh, they definitely should not. They used to be under "content" right? I'll move them back...
